name: Run Examples

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-examples:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set MUFEM version from VERSION file
      run: | 
        echo "MUFEM_VERSION=$(cat VERSION)" >> $GITHUB_ENV
        echo "$HOME/mufem" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r .requirements.txt

    - name: Install mufem
      run: |
        cd $HOME
        wget -q http://www.raiden-numerics.com/downloads/mufem-${MUFEM_VERSION}.zip
        unzip -q mufem-${MUFEM_VERSION}.zip

    - name: Run the examples
      run: |
        cd $GITHUB_WORKSPACE
        python3 ./run_cases.py

