name: Run Examples

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set MUFEM version from VERSION file
      run: | 
        echo "MUFEM_VERSION=$(cat VERSION)" >> $GITHUB_ENV
        echo "$HOME/mufem" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install mufem
      run: |
        cd $HOME
        wget -q http://www.raiden-numerics.com/downloads/mufem-${MUFEM_VERSION}.zip
        unzip -q mufem-${MUFEM_VERSION}.zip

    - name: Verify ls
      run: |
       echo $PATH
       ls -l

    - name: Verify ls2


    - name: Verify pymufem installation
      run:  command -v pymufem
      env:
        PATH: ~/mufem:$PATH

    - name: Run the examples
      run: |
        cd $GITHUB_WORKSPACE
        echo $HOME
        echo $PWD
        command -v pymufem
        python3 ./run_cases.py

